### ISSUE TITLE
Clean up styleguide styling logic

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#197]
In order to prepare for the upcoming “Bedrock bases” feature, we need to do some cleanup work.

* [x]  #199 Remove bedrock dark styles, and bedrock dark config option
* [x] #200 Remove base styles for .br-content headings etc. from `core`; move these to `content`. The styling for these is project specific.
* [x] #201 Add a guide on how to style the style guide to your specific project

**Comment by Wolfr** [comment]
I changed my mind on #200 , I kept some base styles in `core` and then the idea is that you configure the styleguide look based on your project's CSS (easy mode which also is easily upgradable to newer versions of Bedrock) or override the templates (advanced mode, useful for custom projects, but might make upgrading Bedrock a problem).
