### ISSUE TITLE
Feedback from call 4 dec

### ISSUE THREAD

**Issue by Wolfr** [usebedrock/bedrock#50]
### Gear detail
- On a piece of gear, add an index of the oil samples taken (list) -- by component
  - Engine, Transmission, Converter
  - Every 500 hours you get samples: so dates are for example X weeks apart
  - Severity level might be on of the columns
### Service issue
- Service issue from fault code
  - Ask David for example
### Service issue from form
- Visual - Change to soft red --> http://cl.ly/image/3k383M1e2927/Screen%20Shot%202015-12-04%20at%2016.22.54.png
### Admin > Gear import
- Allow the user to download an example CSV --> to edit
### Feed
- For every feed, link a username to /modules/users/detail.html

CSV: unit number, type, manufacturer, model, hours, mileage
### User
- http://localhost:3000/modules/users/edit.html
- Add the third role in the modal http://cl.ly/image/2b3a2a110r1z/Screen%20Shot%202015-12-04%20at%2016.15.40.png
- Remove the delete icon, put the deletion inside the modal, also add functionality to disable an account
- Add a column with subtle text next to "Role" that has different Statusses for an account: Active, Pending, Disabled
### General navigation
- [ ] Make the group list have a big bigger targets http://cl.ly/image/0I0B0P1q2B2d/Screen%20Shot%202015-12-04%20at%2016.02.23.png
### Gear overview
- [ ] Gear - Full map view should be implemented
- [ ] Gear list: vary the color on the 4th level --> last one is the one you an click, 
- [ ] add expand all button
### Dashboard

Name column on dashboard doesn't need to be there (tasks widget)
- Add group page
- [ ] Capitalize "My Groups" and check across the platform for capitalization
### Tasks overview
- Assignee should be a column
- This icon is really light: http://cl.ly/image/2D103V0c3I3w/Screen%20Shot%202015-12-04%20at%2015.43.05.png it should be darker
- 2 ways of working:
  - 1 is me-centric: tasks assigned to me, tasks I've created, tasks I'm mentioned in
  - Other is "other person centric":
    - Current list of people (checkboxes) should be a dropdown
- Think the filter logic through on tasks, because now it's bad
### Group overview

http://localhost:3000/modules/groups/dashboard.html

modules/groups/dashboard.html --> gear widget: add expand all button
### Discussions

http://localhost:3000/modules/groups/discussions.html
### Notifications

Notifications: Have # in front of number http://cl.ly/image/2s1Q1n442E2a/Screen%20Shot%202015-12-04%20at%2016.10.02.png

Add example:
- Assigned a task
- Shared a discussion with you
- Add some context: "in group" "in company"
### Add discussion

http://localhost:3000/modules/discussions/add
- Add discussion should be a modal
- Looks too bare, needs "Add" button to add the discussion, also a cancel button
- You need to select who to notify
### Discussion view
- Add an example of a third party coming in to comment on a discussion
